### PR TITLE
Github actions CI

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
You don't use TEST_LANG in "result.nimble".

**Comment by arnetheduck** [comment]
thanks, is there an example somewhere that shows how to compile on multiple nim versions as well?

**Comment by stefantalpalaru** [comment]
Yes: https://github.com/status-im/nim-metrics/blob/master/.github/workflows/ci.yml

**Comment by arnetheduck** [comment]
> Yes: https://github.com/status-im/nim-metrics/blob/master/.github/workflows/ci.yml

alright, I think I nailed it here, though it looks like it disables the caching, right?

**Comment by stefantalpalaru** [comment]
Yes, because it makes no sense to cache something that changes often.

**Comment by arnetheduck** [comment]
> Yes, because it makes no sense to cache something that changes often.

v1.2/v1.4 is pretty stable though, and I think I'll limit testing to that - indeed because devel is too much of a breaking and moving target that spending effort on chasing down every failure there takes too much time

**Comment by arnetheduck** [comment]
> You can also let the devel job run, but tell the system to ignore its failure: https://github.com/status-im/nimbus-eth2/blob/44f652f704f14c67e648f2b14dee652d44b858c5/.github/workflows/cron.yml#L44

indeed, this is what we want to do for any currently unsupported versions, for status projects (ie anything not 1.2)

**Pull request merged**
